[package]
name = "renode-ebreak-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-halt = "0.2.0"

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv-rt = "0.11"
